# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f14f0bac6a88d3e8faecd961b4c7c11eb278aebeacb9f6568087f1d56badb97f409a329b250da383790bb603ea0c473edd061527298fa4e79577730e2feada1

test:
  secret_key_base: cff53bb3c48729bf509a474b20b1e9cc3b5a494da90866d5a8d76bcad17e638d530499e7148af70389b4d16170306d37cccef09f076fba2df3c9bdd80fbef7ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
